db:
 image: mariadb
 environment:
  - MYSQL_ROOT_PASSWORD=root
 ports:
  - 3307:3306

php:
 image: jprjr/php-fpm
 ports:
  - 9000:9000
 links:
  - db:db
 volumes:
  - ./web/:/srv/http:ro

web:
 image: nginx
 ports:
  - 80:80
 links:
  - php:php
 volumes:
  - ./web/:/usr/share/nginx/html:ro
  - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro

myadmin:
 image: phpmyadmin/phpmyadmin
 ports:
  - 8080:80
 links:
  - db:db
